apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-store
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-store
  chart:
    git: ssh://git@github.com/bob-fly/blockchain-automation-framework.git
    ref: test
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: store-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: reg.hrlyit.com/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.store-net:7051
      localmspid: storeMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://sibo.local:8200
      authpath: dev2store-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/store-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/store-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CpYCChAKDggCIgphbGxjaGFubmVsEoECCv4BCgphbGxjaGFubmVsElgSVgoLQXBwbGljYXRpb24SRwgBEjsKCHN0b3JlTVNQEi8aBwoDTVNQEgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACoGQWRtaW5zGpUBEpIBCgtBcHBsaWNhdGlvbhKCAQgBEnYKCHN0b3JlTVNQEmoIARoHCgNNU1ASABovCgtBbmNob3JQZWVycxIgEhYKFAoPcGVlcjAuc3RvcmUtbmV0EIs3GgZBZG1pbnMiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACoGQWRtaW5zKgZBZG1pbnM=

