apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-peer0
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: store-peer0
  chart:
    git: ssh://git@github.com/bob-fly/blockchain-automation-framework.git
    ref: test
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: store-net
      images:
        couchdb: hyperledger/fabric-couchdb:0.4.14
        peer: hyperledger/fabric-peer:1.4.0
        alpineutils: reg.hrlyit.com/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
        
    peer:
      name: peer0
      gossippeeraddress: peer0.store-net:7051
      gossipexternalendpoint: peer0.store-net:7051
      localmspid: storeMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:1.4.0
      couchdb:
        username: store-user

    storage:
      peer:
        storageclassname: storesc
        storagesize: 512Mi
      couchdb:
        storageclassname: storesc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://sibo.local:8200
      authpath: dev2store-net-auth
      secretprefix: secret/crypto/peerOrganizations/store-net/peers/peer0.store-net
      secretambassador: secret/crypto/peerOrganizations/store-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/store-net/couchdb/store?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "none"
      external_url_suffix: org3ambassador.blockchaincloudpoc.com
