apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-net-ca
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: warehouse-net-ca
  chart:
    git: ssh://git@github.com/bob-fly/blockchain-automation-framework.git
    ref: test
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: warehouse-net
      images:
        alpineutils: reg.hrlyit.com/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.4
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
       
    server:
      name: ca
      tlsstatus: true
      admin: warehouse-admin
    storage:
      storageclassname: warehousesc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://sibo.local:8200
      authpath: dev2warehouse-net-auth
      secretcert: secret/crypto/peerOrganizations/warehouse-net/ca?ca.warehouse-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/warehouse-net/ca?warehouse-net-CA.key
      secretadminpass: secret/credentials/warehouse-net/ca/warehouse?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: org2ambassador.blockchaincloudpoc.com
