apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-net-ca-tools
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-net-ca-tools
  chart:
    git: ssh://git@github.com/bob-fly/blockchain-automation-framework.git
    ref: test
    path: platforms/hyperledger-fabric/charts/catools
  values:
    metadata:
      namespace: carrier-net
      name: ca-tools
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    replicaCount: 1

    image:
      repository: hyperledger/fabric-ca-tools
      tag: 1.2.1
      pullPolicy: IfNotPresent
      
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
