kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storesc
provisioner: fuseim.pri/ifs
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  encrypted: "true"
  archiveOnDelete: "true"