apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-peer0
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: warehouse-peer0
  chart:
    git: ssh://git@github.com/bob-fly/blockchain-automation-framework.git
    ref: test
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: warehouse-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.0
        alpineutils: reg.hrlyit.com/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
        
    peer:
      name: peer0
      gossippeeraddress: peer0.warehouse-net:7051
      gossipexternalendpoint: peer0.warehouse-net:7051
      localmspid: warehouseMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.0
      couchdb:
        username: warehouse-user

    storage:
      peer:
        storageclassname: warehousesc
        storagesize: 512Mi
      couchdb:
        storageclassname: warehousesc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://172.16.200.174:8200
      authpath: dev2warehouse-net-auth
      secretprefix: secret/crypto/peerOrganizations/warehouse-net/peers/peer0.warehouse-net
      secretambassador: secret/crypto/peerOrganizations/warehouse-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/warehouse-net/couchdb/warehouse?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "none"
      external_url_suffix: org2ambassador.blockchaincloudpoc.com
