apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-net-ca
  chart:
    git: ssh://git@github.com/bob-fly/blockchain-automation-framework.git
    ref: test
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: carrier-net
      images:
        alpineutils: reg.hrlyit.com/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    deployment:
      annotations:
    annotations:  
      service:
        - example1: example2
      pvc:
       
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://172.16.200.174:8200
      authpath: dev2carrier-net-auth
      secretcert: secret/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: secret/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: none
      type: peer
      external_url_suffix: org3ambassador.blockchaincloudpoc.com
